version: "3.9"

services:
    api:
        build: 
          context: ./
          dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
          db:
            condition: service_started

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_USER: "test"
            MYSQL_PASSWORD : "test"
            MYSQL_DATABASE : "invoicemanager"